### PR TITLE
Support for TKSmartCard

### PR DESCRIPTION
**Pull request by jensutbult**
Adding support for TKSmartCard to the SDK. This will allow most of the applications on the YubiKey to work on an iPad running iOS 16 with USB-C port.

### CODE REVIEW

**Comment by WWSellers** [comment]
Are there any instructions on what we should change to test this branch? I did not see any changes to README.md

**Comment by WWSellers** [comment]
I tried this on an iPad Pro with USB-C connector.  It did not display a prompt to get the user to connect the YubiKey.

**Comment by jensutbult** [comment]
This is still a draft PR and documentation will be added later. For now you should be able to add support for USB-C via the TKSmartCard interface in applications that uses the SDK. This connection behaves much like the current lightning connection. You implement the delegate methods for smart card connection and call `startSmartCardConnection()`. Once a USB-C YubiKey is inserted the corresponding delegate methods will be called. Note that there is no prompt displayed by iOS.

**Comment by WWSellers** [comment]
I ran a quick test, getting pivSession from the smartcard interface on iPad Pro with USB-C.  It read from pivSession without any noticeable error.  (The test did not include signing or encryption operations.)
Model: "iPad8,1" which lacks NFC hardware.

**Pull request merged**
